### ISSUE TITLE
chat error

### ISSUE THREAD

**Issue by YTiceice** [WiIIiam278/HuskChat#186]
When player send any message, plugin will show this error in console:
```
[17:00:16 ERROR]: Could not pass event AsyncPlayerChatEvent to HuskChat v2.7.1
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.handle(CraftScheduler.java:533) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:233) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:209) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:173) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.runTask(CraftScheduler.java:142) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.william278.huskchat.bukkit.event.BukkitEventDispatcher.dispatchChatMessageEvent(BukkitEventDispatcher.java:47) ~[HuskChat-Plugin-2.7.1.jar:?]
        at net.william278.huskchat.message.ChatMessage.dispatch(ChatMessage.java:113) ~[HuskChat-Plugin-2.7.1.jar:?]
        at net.william278.huskchat.bukkit.listener.BukkitListener.onPlayerChat(BukkitListener.java:49) ~[HuskChat-Plugin-2.7.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor442.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:68) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:414) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:100) ~[kaiiju-1.20.1.jar:git-Kaiiju-"c2b7aec"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2510) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2662) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$15(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

I am using Folia fork (Kaiiju), maybe the plugin made a mistake?

**Comment by WiIIiam278** [comment]
Hey there, please install FreedomChat for 1.19+ support on Bukkit :)
