### ISSUE TITLE
UnsupportedOperationException are thrown when chatting

### ISSUE THREAD

**Issue by MATRIX-feather** [WiIIiam278/HuskChat#226]
### Description
Each time someone chats on a channel, the console throws an UnsupportedOperationException.

The server version is `git-Folia-"25ee657"` and the plugin is `3.0.4-8ad4c4d`

### Log
```
[21:33:44 ERROR]: Could not pass event AsyncPlayerChatEvent to HuskChat v3.0.4-8ad4c4d
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTask(CraftScheduler.java:144) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.william278.huskchat.event.BukkitEventProvider.fireChatMessageEvent(BukkitEventProvider.java:37) ~[HuskChat-Plugin-3.0.4-8ad4c4d.jar:?]
        at net.william278.huskchat.message.ChatMessage.dispatch(ChatMessage.java:111) ~[HuskChat-Plugin-3.0.4-8ad4c4d.jar:?]
        at net.william278.huskchat.listener.BukkitListener.onPlayerChat(BukkitListener.java:54) ~[HuskChat-Plugin-3.0.4-8ad4c4d.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor56.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"25ee657"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2373) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2503) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.java:2221) ~[?:?]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:27) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by mani1232** [comment]
```
[23:55:12 ERROR]: Could not pass event AsyncPlayerChatEvent to HuskChat v3.0.4
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:175) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.runTask(CraftScheduler.java:144) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at HuskChat-3.0.4 (1).jar/net.william278.huskchat.event.BukkitEventProvider.fireChatMessageEvent(BukkitEventProvider.java:37) ~[HuskChat-3.0.4 (1).jar:?]
        at HuskChat-3.0.4 (1).jar/net.william278.huskchat.message.ChatMessage.dispatch(ChatMessage.java:111) ~[HuskChat-3.0.4 (1).jar:?]
        at HuskChat-3.0.4 (1).jar/net.william278.huskchat.listener.BukkitListener.onPlayerChat(BukkitListener.java:54) ~[HuskChat-3.0.4 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor27.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-DEV-81dd04e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[luminol-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2446) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:2563) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$12(ServerGamePacketListenerImpl.java:2218) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:25) ~[luminol-1.20.6.jar:1.20.6-DEV-81dd04e]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:55:12 INFO]: <mani1232> j
```
1.20.6 too
