### ISSUE TITLE
[Feature Request]: Add support for velocity because waterfall is EOL

### ISSUE THREAD

**Issue by SJ-Tom** [WiIIiam278/HuskChat#239]
`
[13:05:36 ERROR]: Couldn't pass ProxyInitializeEvent to huskchat 3.0.4
java.lang.IllegalArgumentException: Command must have at least one alias
        at net.william278.huskchat.command.CommandBase.<init>(CommandBase.java:44) ~[?:?]
        at net.william278.huskchat.command.ChannelCommand.<init>(ChannelCommand.java:36) ~[?:?]
        at net.william278.huskchat.command.VelocityCommand$Type.lambda$static$1(VelocityCommand.java:82) ~[?:?]
        at net.william278.huskchat.command.VelocityCommand$Type.register(VelocityCommand.java:103) ~[?:?]
        at net.william278.huskchat.command.VelocityCommand$Type.lambda$registerAll$8(VelocityCommand.java:107) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.william278.huskchat.command.VelocityCommand$Type.registerAll(VelocityCommand.java:107) ~[?:?]
        at net.william278.huskchat.VelocityHuskChat.onProxyInitialization(VelocityHuskChat.java:138) ~[?:?]
        at net.william278.huskchat.Lmbda$5.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-386.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-386.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-386.jar:3.3.0-SNAPSHOT (git-399bc232-b386)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
`

**Comment by WiIIiam278** [comment]
Velocity is supported.

**Comment by SJ-Tom** [comment]
Why do I get this error in the console and the plugin does not work?

**Comment by WiIIiam278** [comment]
Bad config - looks like you haven't specified any aliases for a command. Regen your config.yml file first.

**Comment by SJ-Tom** [comment]
Nope emoji replacements unfortunately does not work

**Comment by WiIIiam278** [comment]
Yep, that's a known separate issue
