### ISSUE TITLE
Jep library loading error when setting a path manually for profanity checker

### ISSUE THREAD

**Issue by WiIIiam278** [WiIIiam278/HuskChat#92]
<details>
<summary>Relevant logs</summary>

```log
10:04:09 [WARNING] Exception encountered when loading plugin: HuskChat
java.lang.RuntimeException: Failed to initialize ProfanityChecker (Jep.setJepLibraryPath(...) called after initializing python interpreter.)Please ensure that the jep library is installed and the library path is correct. Consult the HuskChat docs for more 
information on this error.
    at net.william278.huskchat.filter.ProfanityFilterer.initialize(ProfanityFilterer.java:38)
    at net.william278.huskchat.filter.ProfanityFilterer.<init>(ProfanityFilterer.java:28)
    at net.william278.huskchat.config.Settings.fetchChatFilters(Settings.java:301)
    at net.william278.huskchat.config.Settings.load(Settings.java:149)
    at net.william278.huskchat.bungeecord.HuskChatBungee.reloadSettings(HuskChatBungee.java:179)
    at net.william278.huskchat.bungeecord.HuskChatBungee.onEnable(HuskChatBungee.java:84)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:295)

    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.IllegalStateException: Jep.setJepLibraryPath(...) called after initializing python interpreter.
    at jep.MainInterpreter.setJepLibraryPath(MainInterpreter.java:287)
    at net.william278.huskchat.libraries.profanitycheckerapi.ProfanityChecker.initialize(ProfanityChecker.java:81)
    at net.william278.huskchat.libraries.profanitycheckerapi.ProfanityChecker.<init>(ProfanityChecker.java:63)
    at net.william278.huskchat.libraries.profanitycheckerapi.ProfanityCheckerBuilder.build(ProfanityCheckerBuilder.java:84)
    at net.william278.huskchat.filter.ProfanityFilterer.initialize(ProfanityFilterer.java:35)
    ... 9 more
```

</details>

**Comment by WiIIiam278** [comment]
Should be fixed in #196
